In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing CSV file using Pandas and displaying 5 rows

In [2]:
df = pd.read_csv("C:/MLCourse/Databaseforml/spotifydata.csv")
df.head()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.0102,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.1990,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.0344,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.6040,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.1800,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys

Displaying top 10 rows

In [3]:
df.head(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
0,0,0.01020,0.833,204600,0.434,0.021900,2,0.1650,-8.795,1,0.4310,150.062,4.0,0.286,1,Mask Off,Future
1,1,0.19900,0.743,326933,0.359,0.006110,1,0.1370,-10.401,1,0.0794,160.083,4.0,0.588,1,Redbone,Childish Gambino
2,2,0.03440,0.838,185707,0.412,0.000234,2,0.1590,-7.148,1,0.2890,75.044,4.0,0.173,1,Xanny Family,Future
3,3,0.60400,0.494,199413,0.338,0.510000,5,0.0922,-15.236,1,0.0261,86.468,4.0,0.230,1,Master Of None,Beach House
4,4,0.18000,0.678,392893,0.561,0.512000,5,0.4390,-11.648,0,0.0694,174.004,4.0,0.904,1,Parallel Lines,Junior Boys
5,5,0.00479,0.804,251333,0.560,0.000000,8,0.1640,-6.682,1,0.1850,85.023,4.0,0.264,1,Sneakin’,Drake
6,6,0.01450,0.739,241400,0.472,0.000007,1,0.2070,-11.204,1,0.1560,80.030,4.0,0.308,1,Childs Play,Drake
7,7,0.02020,0.266,349667,0.348,0.664000,10,0.1600,-11.609,0,0.0371,144.154,4.0,0.393,1,Gyöngyhajú lány,Omega
8,8,0.04810,0.603,202853,0.944,0.000000,11,0.3420,-3.626,0,0.3470,130.035,4.0,0.398,1,I've Seen Footage,Death Grips
9,9,0.00208,0.836,226840,0.603,0.000000,7,0.5710,-7.792,1,0.2370,99.994,4.0,0.386,1,Digital Animal,Honey Claws

Displaying bottom 5 rows

In [4]:
df.tail()

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2012,2012,0.00106,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.333,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.08770,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.131,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.00857,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.107,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.00164,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.133,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.00281,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.141,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

Displaying bottom 10 rows

In [5]:
df.tail(10)

,Unnamed: 0,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence,target,song_title,artist
2007,2007,0.002170,0.639,296276,0.978,0.112000,11,0.0838,-2.376,1,0.0730,144.986,4.0,0.494,0,Let It Go - Scott Melker & Mister Gray Remix,NERVO
2008,2008,0.054100,0.646,160408,0.714,0.000000,0,0.1340,-6.511,1,0.0378,97.957,4.0,0.589,0,"Call On Me - EDWYNN X TIKAL, Spirix Remix",Starley
2009,2009,0.004990,0.595,224000,0.837,0.035900,1,0.1010,-6.011,1,0.0696,149.964,4.0,0.331,0,Aamon,Kuuro
2010,2010,0.002310,0.624,206013,0.971,0.121000,6,0.2550,-0.935,0,0.0643,102.003,4.0,0.442,0,Hey Baby - Steve Aoki Remix,Dimitri Vegas & Like Mike
2011,2011,0.000586,0.528,245053,0.879,0.004890,6,0.0432,-5.891,0,0.1200,128.268,4.0,0.327,0,Brightside - Borgeous Remix,Icona Pop
2012,2012,0.001060,0.584,274404,0.932,0.002690,1,0.1290,-3.501,1,0.3330,74.976,4.0,0.211,0,Like A Bitch - Kill The Noise Remix,Kill The Noise
2013,2013,0.087700,0.894,182182,0.892,0.001670,1,0.0528,-2.663,1,0.1310,110.041,4.0,0.867,0,Candy,Dillon Francis
2014,2014,0.008570,0.637,207200,0.935,0.003990,0,0.2140,-2.467,1,0.1070,150.082,4.0,0.470,0,Habit - Dack Janiels & Wenzday Remix,Rain Man
2015,2015,0.001640,0.557,185600,0.992,0.677000,1,0.0913,-2.735,1,0.1330,150.011,4.0,0.623,0,First Contact,Twin Moons
2016,2016,0.002810,0.446,204520,0.915,0.000039,9,0.2180,-6.221,1,0.1410,190.013,4.0,0.402,0,I Wanna Get Better,Bleachers

Using .info function to have a look at the Data type and null values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2017 entries, 0 to 2016
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2017 non-null   int64
 1   acousticness      2017 non-null   float64
 2   danceability      2017 non-null   float64
 3   duration_ms       2017 non-null   int64
 4   energy            2017 non-null   float64
 5   instrumentalness  2017 non-null   float64
 6   key               2017 non-null   int64
 7   liveness          2017 non-null   float64
 8   loudness          2017 non-null   float64
 9   mode              2017 non-null   int64
 10  speechiness       2017 non-null   float64
 11  tempo             2017 non-null   float64
 12  time_signature    2017 non-null   float64
 13  valence           2017 non-null   float64
 14  target            2017 non-null   int64
 15  song_title        2017 non-null   object
 16  artist            2017 non-null   object
dtypes: float64(10), int64(5), object(2)
memory usage: 268.0+ KB

Sorting on basis of danceability and displaying top 10 song title

In [7]:
df.sort_values('danceability')[['song_title']].head(10)

                                             song_title
729                                          Bumpy Road
532                                     Wake Bake Skate
817   Mozart: Requiem in D Minor, K. 626: VIII. Lacr...
1600         Trio Sonata in G Major, Wq. 144: I. Adagio
1598  Piano Quartet in E flat, Op.47: 3. Andante can...
522                                               Outro
1348               Be My Valentine (feat. Dickie Allen)
1464                                         Right Here
1313                                    Senseless Order
1306                                               Ruin

Same as previous one, just displaying an extra column artist

In [8]:
df.sort_values('danceability')[['song_title', 'artist']].head(10)

,song_title,artist
729,Bumpy Road,Destruction Unit
532,Wake Bake Skate,FIDLAR
817,"Mozart: Requiem in D Minor, K. 626: VIII. Lacr...",Nikolaus Harnoncourt
1600,"Trio Sonata in G Major, Wq. 144: I. Adagio",Carl Philipp Emanuel Bach
1598,"Piano Quartet in E flat, Op.47: 3. Andante can...",Robert Schumann
522,Outro,M83
1348,Be My Valentine (feat. Dickie Allen),Brojob
1464,Right Here,Keys N Krates
1313,Senseless Order,Signs of the Swarm
1306,Ruin,Altered Perceptions

Sorting on basis of duration of song and displaying top 10 song title, artists and duration

In [9]:
df.sort_values('duration_ms')[['song_title','artist','duration_ms']].head(10)

                                   song_title            artist  duration_ms
1044             Zac Brown Band - Hot Country   Various Artists        16042
1436                               dance alot   Various Artists        16588
1591                       Little Green Apple       Tumble Tots        47547
1583                         Peas Pudding Hot     The Kids Band        51547
936                                     Aloha        Chris Bear        52006
1530                   I'm a Fool to Want You  Passport Quartet        66762
1594  Lyric Pieces, Book I Op. 12: I. Arietta      Edvard Grieg        82293
804                  Just Wanna Love You Girl          Epsilons        82893
1593                    Icy, Creamy Ice Cream            Barney        87705
533                                    No Ass            FIDLAR        93267

Creating a new dataframe and storing only those values which have duration less than 400000 ms

In [10]:
temp_df = df[df['duration_ms']<400000]

Sorting new dataframe in ascending on basis of energy and displaying  bottom 10

In [11]:
temp_df2 = temp_df.sort_values('energy')[['song_title','artist','duration_ms','energy']].tail(10)
temp_df2.head()

               song_title               artist  duration_ms  energy
1296         Black Colors  Victim Of Deception       247533   0.990
1681                Hated            Beartooth       211430   0.990
1328  Down into the Abyss          Conjonctive       256920   0.991
1680             Paranoia    A Day To Remember       200677   0.992
1332      Beautiful Agony     Within The Ruins       271560   0.992

Sorting values on basis of energy in descending order

In [12]:
ans = temp_df2.sort_values('energy', ascending=False)

Sorting on basis of duration and exporting CSV file

In [13]:
df_filtered = df.sort_values('duration_ms')[['song_title', 'artist', 'duration_ms']].tail(10)
df_filtered.to_csv('D:\ML Files\spotify_filtered_data.csv')

keeping only that data which has energ value greater than 0.4, only keeping song title and artists

In [14]:
temp_df = df[df['energy']>0.4]
temp_df[['song_title','artist']].head(10)

                              song_title              artist
0                               Mask Off              Future
2                           Xanny Family              Future
4                         Parallel Lines         Junior Boys
5                               Sneakin’               Drake
6                            Childs Play               Drake
8                      I've Seen Footage         Death Grips
9                         Digital Animal         Honey Claws
10  Subways - In Flagranti Extended Edit      The Avalanches
11            Donme Dolap - Baris K Edit  Modern Folk Üçlüsü
12                               Cemalim         Erkin Koray

keeping only that data, in which duration is greater than 3000000

In [15]:
temp_df = df[df['duration_ms']>300000]

Sorting on basis of tempo column and displaying top 10

In [16]:
temp_df2 = temp_df.sort_values('tempo',ascending = False)[['song_title','artist']].head(10)
temp_df2.head()

                                             song_title            artist
412                                              Lazuli       Beach House
942                                            Remember       Gino Soccio
729                                          Bumpy Road  Destruction Unit
1560                       Emperor Jones - Instrumental        Joe Lovano
992   Swerve... the reeping of all that is worthwhil...   Shabazz Palaces

Keeping only those rows, with Drake as artist and energy greater than 0.5

In [17]:
temp_df = df[df['artist'] == 'Drake']

In [18]:
temp_df2 = temp_df[temp_df['energy']>0.5]

In [19]:
temp_df2[['song_title']].head(10)

                   song_title
5                    Sneakin’
37                    Jumpman
117             Hotline Bling
154                 Big Rings
440                 Headlines
589   Started From the Bottom
779   0 To 100 / The Catch Up
1016         Skepta Interlude
1218          Best I Ever Had
1223                Take Care

Sort values in descending order on basis of instrumentalness

In [20]:
temp_df = df.sort_values('instrumentalness',ascending = False)[['song_title','artist','instrumentalness']]
temp_df.head(10)

,song_title,artist,instrumentalness
1313,Senseless Order,Signs of the Swarm,0.976
271,So Destroyed (channeling Rage Peace),Prince Rama,0.968
1575,A Hundred Dreams from Now,Ray Bryant,0.964
1619,Raven,John Dahlbäck,0.958
725,Strandbar (disko),Todd Terje,0.957
1546,Almas vaggvisa,Jan Lundgren Trio,0.956
1322,Pitchblack,Walking Dead On Broadway,0.955
1349,Prismatic Abyss,Aversions Crown,0.954
1661,Yebisah,Mark Knight,0.954
121,Chasing Heaven,Bassnectar,0.952